src/main/java/com/emerdaf/app/web/ClientBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emerdaf.app.web;

import com.emerdaf.app.domain.CompteEntity;
import com.emerdaf.app.domain.security.UserEntity;
import com.emerdaf.app.service.CompteService;
import com.emerdaf.app.service.security.SecurityWrapper;
import com.emerdaf.app.service.security.UserService;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.inject.Inject;

/**
 *
 * @author Norah
 */
@Named(value = "clientBean")
@SessionScoped
public class ClientBean implements Serializable {

    @Inject
    private UserService userService;
//

    private int[] nbreEnfParNiveau = new int[7];
    
    @Inject
    private CompteService compteService;
//
    private UserEntity client;
    private CompteEntity compte;
    private List<CompteEntity> comptes = new ArrayList<>();
//
//    private int[] nbreEnfParNiveau = new int[7];
//
//    private TreeNode root;
//    private TreeNode selectedNode;
//

    public ClientBean() {
    }

    @PostConstruct
    public void init() {
        String username = SecurityWrapper.getUsername();
        if (username != null) {
            this.client = this.userService.findUserByUsername(username);
        } else {
            throw new RuntimeException("Can not get authorized user name");
        }

    }
//

    public UserEntity getClient() {
        if (client == null) {
            client = new UserEntity();
        }
        return client;
    }

    public void setClient(UserEntity client) {
        this.client = client;
    }

    public CompteEntity getCompte() {
        if (compte == null) {
            compte = new CompteEntity();
        }
        return compte;
    }

    public void setCompte(CompteEntity compte) {
        this.compte = compte;
    }

    public List<CompteEntity> getComptes() {
        return compteService.findComptesByClient(client);
    }

    public void setComptes(List<CompteEntity> comptes) {
        this.comptes = comptes;
    }
//
//    public List<CompteEntity> getEnfants() {
//        return compteService.getCmptEnfants(compte);
//    }
//
//    public void setEnfants(List<CompteEntity> enfants) {
//        this.enfants = enfants;
//    }
//
//    public CompteEntity getNoeudParent() {
//        return compteService.findNoeudCompteParentByCompteEnfant(compte);
//    }
//
//    public void setNoeudParent(CompteEntity noeudParent) {
//        this.noeudParent = noeudParent;
//    }
//
//    public TreeNode getSelectedNode() {
//        return selectedNode;
//    }
//
//    public void setSelectedNode(TreeNode selectedNode) {
//        this.selectedNode = selectedNode;
//    }
//
//    public int[] getNbreEnfParNiveau() {
//        return nbreEnfParNiveau;
//    }
//
//    public void setNbreEnfParNiveau(int[] nbreEnfParNiveau) {
//        this.nbreEnfParNiveau = nbreEnfParNiveau;
//    }
//
//    public String loadCmpt(CompteEntity c) {
//        this.setCompte(c);
//        root = new DefaultTreeNode(c, null);
////        for (int i = 0; i < 3; i++) {
////            nodes.add(new DefaultTreeNode(null, root));
////        }
//        return "/pages/compte/cmptView?faces-redirect=true";
//    }
//
//    public TreeNode getRoot() {
//        return root;
//    }
//
//    public void onNodeExpand(NodeExpandEvent event) {
//        CompteEntity c = (CompteEntity) event.getTreeNode().getData();
//        System.out.println("\n\nc2 = " + c.getCategorie());
////        List<CompteEntity> enfs = compteService.getCmptEnfants(compte);
////
//////        nodes.clear();
////        for (CompteEntity enf : enfs) {
////            System.out.println("\n\nenf = " + enf);
////            nodes.add(new DefaultTreeNode(enf, root));
////        }
//    }
//
//    public void onNodeSelect(NodeSelectEvent event) {
//        CompteEntity c = (CompteEntity) event.getTreeNode().getData();
//        System.out.println("\n\nc2 = " + c.getCategorie());
//        List<CompteEntity> enfs = compteService.getCmptEnfants(compte);
//
////        nodes.clear();
//        for (CompteEntity enf : enfs) {
//            nodes.add(new DefaultTreeNode(enf, root));
//        }
//    }
//
//    public List<CompteEntity> getEnfs(CompteEntity c) {
//        return compteService.getCmptEnfants(c);
//    }

    public int getNbreEnfs(CompteEntity c) {
        int x1, x2 = 0, x3 = 0, x4 = 0, x5 = 0, x6 = 0, x7 = 0;

        List<CompteEntity> l1 = compteService.getCmptEnfants(c);
        x1 = l1.size();
        for (CompteEntity n1 : l1) {
            List<CompteEntity> l2 = compteService.getCmptEnfants(n1);
            x2 = x2 + l2.size();
            for (CompteEntity n2 : l2) {
                List<CompteEntity> l3 = compteService.getCmptEnfants(n2);
                x3 = x3 + l3.size();
                for (CompteEntity n3 : l3) {
                    List<CompteEntity> l4 = compteService.getCmptEnfants(n3);
                    x4 = x4 + l4.size();
                    for (CompteEntity n4 : l4) {
                        List<CompteEntity> l5 = compteService.getCmptEnfants(n4);
                        x5 = x5 + l5.size();
                        for (CompteEntity n5 : l5) {
                            List<CompteEntity> l6 = compteService.getCmptEnfants(n5);
                            x6 = x6 + l6.size();
                            for (CompteEntity n6 : l6) {
                                List<CompteEntity> l7 = compteService.getCmptEnfants(n6);
                                x7 = x7 + l7.size();
                            }
                        }
                    }
                }
            }
        }
        System.out.println("=================");
        System.out.println("x1 = " + x1);
        System.out.println("x2 = " + x2);
        System.out.println("x3 = " + x3);
        System.out.println("x4 = " + x4);
        System.out.println("x5 = " + x5);
        System.out.println("x6 = " + x6);
        System.out.println("x7 = " + x7);
        System.out.println("==================");
        int[] tab = {x1, x2, x3, x4, x5, x6, x7};
        nbreEnfParNiveau = tab;
        return x1 + x2 + x3 + x4 + x5 + x6 + x7;
    }

    
//    public String creerCompte() throws IOException {
//
////        CompteEntity cmpt = new CompteEntity();
//        compte.setClientIndex(this.client);
//        compte.setStatus(CompteStatus.NonPaye);
//        compteService.add(compte);
//        CompteEntity noeud = new CompteEntity();
//        noeud.setCompteindex(compte);
//        compteService.save(noeud);
////        cmpt.setNoeudCompteIndex(noeud);
////        compteService.update2(cmpt);
////        loginBean.login(user.getUsername(), user.getPhone());
////        return null;
//        return "compte.xhtml?faces-redirect=true";
//    }

    public int[] getNbreEnfParNiveau() {
        return nbreEnfParNiveau;
    }

    public void setNbreEnfParNiveau(int[] nbreEnfParNiveau) {
        this.nbreEnfParNiveau = nbreEnfParNiveau;
    }
}

src/main/java/com/emerdaf/app/web/security/UserBean.java
package com.emerdaf.app.web.security;

import com.emerdaf.app.domain.CompteEntity;
import com.emerdaf.app.domain.CompteStatus;
import com.emerdaf.app.domain.NoeudEntity;
import com.emerdaf.app.domain.security.UserEntity;
import com.emerdaf.app.domain.security.UserPays;
import com.emerdaf.app.domain.security.UserProvince;
import com.emerdaf.app.domain.security.UserRole;
import com.emerdaf.app.domain.security.UserStatus;
import com.emerdaf.app.service.CompteService;
import com.emerdaf.app.service.MyService;
import com.emerdaf.app.service.NoeudService;
import com.emerdaf.app.service.security.SecurityWrapper;
import com.emerdaf.app.service.security.UserService;
import com.emerdaf.app.web.CompteBean;
import com.emerdaf.app.web.generic.GenericLazyDataModel;
import com.emerdaf.app.web.util.MessageFactory;
import java.io.IOException;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;
import org.primefaces.event.FlowEvent;

import org.primefaces.model.LazyDataModel;

@Named("userBean")
@ViewScoped
public class UserBean implements Serializable {

    @EJB
    private MyService myService;

    private static final Logger logger = Logger.getLogger(UserBean.class.getName());

    private LazyDataModel<UserEntity> lazyModel;

    private static final long serialVersionUID = 1L;

    private UserEntity user;

    private CompteEntity cmpt;
    private boolean skip;
    private Integer categorie;

    private String codeParent;

    @Inject
    private UserService userService;
    @Inject
    private NoeudService noeudService;

    @Inject
    private CompteBean compteBean;

    private List<UserEntity> admin = new ArrayList<>();

    @Inject
    private CompteService compteService;

    public UserEntity getUser() {
        if (user == null) {
            user = new UserEntity();
        }
        return user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    public Integer getCategorie() {
        return categorie;
    }

    public void setCategorie(Integer categorie) {
        this.categorie = categorie;
    }

    public String getCodeParent() {
        return codeParent;
    }

    public void setCodeParent(String codeParent) {
        this.codeParent = codeParent;
    }

    public void prepareNewUser() {
        this.user = new UserEntity();
        // set any default values now, if you need
    }

    public List<UserEntity> getAdmin() {
        return userService.findAdmin();
    }

    public void setAdmin(List<UserEntity> admin) {
        this.admin = admin;
    }

    public LazyDataModel<UserEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(userService);
        }
        return this.lazyModel;
    }

    public void persist() {

        String message;

        try {

            if (user.getId() != null) {
                user = userService.update(user);
                message = "message_successfully_updated";
            } else {

                // Check if a user with same username already exists
                if (userService.findUserByUsername(user.getUsername()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_username_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }
                // Check if a user with same email already exists            
                if (userService.findUserByEmail(user.getEmail()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_email_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }

                user = userService.save(user);
                message = "message_successfully_created";
            }

        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        FacesMessage facesMessage = MessageFactory.getMessage(message,
                "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
    }

    public String delete() {
        userService.delete(user);
        FacesMessage facesMessage = MessageFactory.getMessage(
                "message_successfully_deleted", "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        reset();
        return null;
    }

    public void reset() {
        user = null;

    }

    public SelectItem[] getRolesSelectItems() {
        SelectItem[] items = new SelectItem[UserRole.values().length];

        int i = 0;
        for (UserRole role : UserRole.values()) {
            String label = MessageFactory.getMessageString(
                    "enumeration_label_user_roles_" + role.toString());
            items[i++] = new SelectItem(role, label == null ? role.toString() : label);
        }
        return items;
    }

    public SelectItem[] getStatusSelectItems() {
        SelectItem[] items = new SelectItem[UserStatus.values().length];

        int i = 0;
        for (UserStatus status : UserStatus.values()) {
            items[i++] = new SelectItem(status, status.toString());
        }
        return items;
    }

    public SelectItem[] getPaysSelectItems() {
        SelectItem[] items = new SelectItem[UserPays.values().length];

        int i = 0;
        for (UserPays pays : UserPays.values()) {
            items[i++] = new SelectItem(pays, getLabelForPays(pays));
        }
        return items;
    }

    public String getLabelForPays(UserPays value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_user_pays_" + value);
        return label == null ? value.toString() : label;
    }

    public SelectItem[] getProvinceSelectItems() {
        SelectItem[] items = new SelectItem[UserProvince.values().length];

        int i = 0;
        for (UserProvince province : UserProvince.values()) {
            items[i++] = new SelectItem(province, getLabelForProvince(province));
        }
        return items;
    }

    public String getLabelForProvince(UserProvince value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_user_province_" + value);
        return label == null ? value.toString() : label;
    }

    public void loadCurrentUser() {
        String username = SecurityWrapper.getUsername();
        if (username != null) {
            this.user = this.userService.findUserByUsername(username);
        } else {
            throw new RuntimeException("Can not get authorized user name");
        }
    }

    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public String creerCompte(int x) throws IOException {
        ArrayList<UserRole> roles = new ArrayList<>();
        roles.add(UserRole.Registered);
        user.setRoles(roles);
        user.setStatus(UserStatus.Active);
        persist();

        UserEntity user1 = userService.findUserByUsername(user.getUsername());

        String codeClient = user.getPays().name().substring(0, 2)
                + "-" + user.getProvince().name().substring(0, 2)
                + "-" + user.getId();
        user1.setCode(codeClient);
        this.setUser(user1);
        persist();

        CompteEntity compte = new CompteEntity();
        compte.setClient(user1);
        compte.setCategorie(getCategorie());
        if (x == 0) {
            compte.setStatus(CompteStatus.NONPAYE);
            compte.setType("CLIENT");
        }
        myService.addCompte(compte, user1);
        NoeudEntity noeudEntity = new NoeudEntity();
        noeudEntity.setCompteEnfant(compte);
        noeudService.save(noeudEntity);

        return "/pages/main.xhtml";
    }

    public boolean isSkip() {
        return skip;
    }

    public void setSkip(boolean skip) {
        this.skip = skip;
    }

    public String onFlowProcess(FlowEvent event) {
        if (skip) {
            skip = false;   //reset in case user goes back
            return "confirm";
        } else {
            return event.getNewStep();
        }
    }
}

src/main/webapp/pages/admin/userCreateInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <o:validateEqual components="emailEditInput emailRepeatEditInput"
                     showMessageFor="emailRepeatEditInput" message="#{messages.user_email_different_input}"/>

    <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">

        <h:outputLabel value="#{messages.field_label_user_username}:" for="usernameEditInput" />
        <p:inputText value="#{userBean.user.username}" id="usernameEditInput" />
        <p:message for="usernameEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_password}:" for="passwordEditInput" />
        <p:password value="#{userBean.user.password}" id="passwordEditInput" required="true" match="passwordRepeatEditInput"/>
        <p:message for="passwordEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_password_repeat}:" for="passwordRepeatEditInput" />
        <p:password value="#{userBean.user.password}" id="passwordRepeatEditInput" required="true"/>
        <p:message for="passwordRepeatEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_email}:" for="emailEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailEditInput" required="true"/>
        <p:message for="passwordEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_email_repeat}:" for="emailRepeatEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailRepeatEditInput" required="true"/>
        <p:message for="emailRepeatEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_roles}:" for="userRoles" />
        <h:selectManyCheckbox value="#{userBean.user.roles}" converter="omnifaces.GenericEnumConverter" id="userRolesSelection" collectionType="java.util.ArrayList">
            <f:selectItems value="#{userBean.rolesSelectItems}" />
        </h:selectManyCheckbox>
        <p:message for="userRolesSelection" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_status}:" for="selectUserStatusInput" />
        <p:selectOneMenu value="#{userBean.user.status}" converter="omnifaces.GenericEnumConverter"  id="selectUserStatusInput" required="true">
            <f:selectItems value="#{userBean.statusSelectItems}" />
        </p:selectOneMenu>
        <p:message for="selectUserStatusInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_phone}:" for="phoneEditInput" />
        <p:inputText value="#{userBean.user.phone}" id="phoneEditInput" 
                     label="#{messages.field_label_user_phone}" />
        <p:message for="phoneEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_prenom}:" for="prenomEditInput" />
        <p:inputText value="#{userBean.user.prenom}" id="prenomEditInput" 
                     label="#{messages.field_label_user_prenom}" />
        <p:message for="prenomEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_nom}:" for="nomEditInput" />
        <p:inputText value="#{userBean.user.nom}" id="nomEditInput" 
                     label="#{messages.field_label_user_nom}" />
        <p:message for="nomEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_postnom}:" for="postnomEditInput" />
        <p:inputText value="#{userBean.user.postnom}" id="postnomEditInput" 
                     label="#{messages.field_label_user_postnom}" />
        <p:message for="postnomEditInput" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_pays}:" for="paysSelect" />
        <p:selectOneMenu value="#{userBean.user.pays}" converter="omnifaces.GenericEnumConverter"  id="paysSelect">
            <f:selectItem noSelectionOption="true" itemLabel="" />
            <f:selectItems value="#{userBean.paysSelectItems}" />
        </p:selectOneMenu>
        <p:message for="paysSelect" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_province}:" for="provinceSelect" />
        <p:selectOneMenu value="#{userBean.user.province}" converter="omnifaces.GenericEnumConverter"  id="provinceSelect">
            <f:selectItem noSelectionOption="true" itemLabel="" />
            <f:selectItems value="#{userBean.provinceSelectItems}" />
        </p:selectOneMenu>
        <p:message for="provinceSelect" display="icon" />

        <h:outputLabel value="#{messages.field_label_user_adresse}:" for="adresseEditInput" />
        <p:inputText value="#{userBean.user.adresse}" id="adresseEditInput" 
                     label="#{messages.field_label_user_adresse}" />
        <p:message for="adresseEditInput" display="icon" />

    </h:panelGrid>

</html>

src/main/webapp/pages/admin/userEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <o:validateEqual components="emailEditInput emailRepeatEditInput"
            showMessageFor="emailRepeatEditInput" message="#{messages.user_email_different_input}"/>

    <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">

        <h:outputLabel value="#{messages.field_label_user_username}:" for="usernameEditInput" />
        <p:inputText value="#{userBean.user.username}" id="usernameEditInput"
            label="#{messages.field_label_user_username}" disabled="#{not request.isUserInRole('Administrator')}" />
        <p:message for="usernameEditInput" display="icon" />
        
        <h:outputLabel value="#{messages.field_label_user_email}:" for="emailEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailEditInput" required="true"
            label="#{messages.field_label_user_email}" disabled="#{not request.isUserInRole('Administrator')}" />
        <p:message for="emailEditInput" display="icon" />
        
        <h:outputLabel value="#{messages.field_label_user_email_repeat}:" for="emailRepeatEditInput" 
            rendered="#{request.isUserInRole('Administrator')}" />
        <p:inputText value="#{userBean.user.email}" id="emailRepeatEditInput" required="true"
            label="#{messages.field_label_user_email_repeat}"
            rendered="#{request.isUserInRole('Administrator')}"/>
        <p:message for="emailRepeatEditInput" display="icon"
            rendered="#{request.isUserInRole('Administrator')}" />
        
        <h:outputLabel value="#{messages.field_label_user_roles}:" for="userRolesSelection"/>
        <p:selectManyCheckbox value="#{userBean.user.roles}" converter="omnifaces.GenericEnumConverter" id="userRolesSelection"
                layout="grid" columns="1">
            <f:selectItems value="#{userBean.rolesSelectItems}" />
        </p:selectManyCheckbox>
        <p:message for="userRolesSelection" display="icon" />
        
        <h:outputLabel value="#{messages.field_label_user_status}:" for="selectUserStatusInput" />
        <p:selectOneMenu value="#{userBean.user.status}" converter="omnifaces.GenericEnumConverter"  id="selectUserStatusInput" required="true">
            <f:selectItems value="#{userBean.statusSelectItems}" />
        </p:selectOneMenu>
        <p:message for="selectUserStatusInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_phone}:" for="phoneEditInput" />
                <p:inputText value="#{userBean.user.phone}" id="phoneEditInput" 
                    label="#{messages.field_label_user_phone}" />
                <p:message for="phoneEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_prenom}:" for="prenomEditInput" />
                <p:inputText value="#{userBean.user.prenom}" id="prenomEditInput" 
                    label="#{messages.field_label_user_prenom}" />
                <p:message for="prenomEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_nom}:" for="nomEditInput" />
                <p:inputText value="#{userBean.user.nom}" id="nomEditInput" 
                    label="#{messages.field_label_user_nom}" />
                <p:message for="nomEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_postnom}:" for="postnomEditInput" />
                <p:inputText value="#{userBean.user.postnom}" id="postnomEditInput" 
                    label="#{messages.field_label_user_postnom}" />
                <p:message for="postnomEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_pays}:" for="paysSelect" />
                <p:selectOneMenu value="#{userBean.user.pays}" converter="omnifaces.GenericEnumConverter"  id="paysSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.paysSelectItems}" />
                </p:selectOneMenu>
                <p:message for="paysSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_province}:" for="provinceSelect" />
                <p:selectOneMenu value="#{userBean.user.province}" converter="omnifaces.GenericEnumConverter"  id="provinceSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.provinceSelectItems}" />
                </p:selectOneMenu>
                <p:message for="provinceSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_adresse}:" for="adresseEditInput" />
                <p:inputText value="#{userBean.user.adresse}" id="adresseEditInput" 
                    label="#{messages.field_label_user_adresse}" />
                <p:message for="adresseEditInput" display="icon" />

    </h:panelGrid>
</html>

src/main/webapp/pages/admin/userViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not security.isPermitted('user:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{security.isPermitted('user:read')}">

        <h:outputText value="#{messages.field_label_user_username}:" />
        <h:outputText value="#{userBean.user.username}" />
    
        <h:outputText value="#{messages.field_label_user_email}:" />
        <h:outputText value="#{userBean.user.email}" />
        
        <h:outputText value="#{messages.field_label_user_roles}:" />
        <p:outputPanel>
            <ui:repeat value="#{userBean.user.roles}" var="role">
                <h:outputText value="#{role}" /><br/>
            </ui:repeat>
        </p:outputPanel>
        
        <h:outputText value="#{messages.field_label_user_status}:" />
        <h:outputText value="#{userBean.user.status.toString()}" />
    
        <h:outputText value="#{messages.field_label_user_createdAt}:" />
        <h:outputText value="#{userBean.user.createdAt}" ><f:convertDateTime type="both" /></h:outputText>
        
        <h:outputText value="#{messages.field_label_user_username}:" />
        <h:outputText value="#{userBean.user.username}" />

        <h:outputText value="#{messages.field_label_user_email}:" />
        <h:outputText value="#{userBean.user.email}" />

        <h:outputText value="#{messages.field_label_user_phone}:" />
        <h:outputText value="#{userBean.user.phone}" />

        <h:outputText value="#{messages.field_label_user_prenom}:" />
        <h:outputText value="#{userBean.user.prenom}" />

        <h:outputText value="#{messages.field_label_user_nom}:" />
        <h:outputText value="#{userBean.user.nom}" />

        <h:outputText value="#{messages.field_label_user_postnom}:" />
        <h:outputText value="#{userBean.user.postnom}" />

        <h:outputText value="#{messages.field_label_user_pays}:" />
        <h:outputText value="#{userBean.getLabelForPays(userBean.user.pays)}" />

        <h:outputText value="#{messages.field_label_user_province}:" />
        <h:outputText value="#{userBean.getLabelForProvince(userBean.user.province)}" />

        <h:outputText value="#{messages.field_label_user_adresse}:" />
        <h:outputText value="#{userBean.user.adresse}" />

    </h:panelGrid>
</html>