src/main/java/com/emerdaf/app/web/CompteBean.java
package com.emerdaf.app.web;

import com.emerdaf.app.domain.CompteEntity;
import com.emerdaf.app.domain.CompteStatus;
import com.emerdaf.app.domain.NoeudEntity;
import com.emerdaf.app.domain.security.UserEntity;
import com.emerdaf.app.service.CompteService;
import com.emerdaf.app.service.NoeudService;
import com.emerdaf.app.service.security.SecurityWrapper;
import com.emerdaf.app.service.security.UserService;
import com.emerdaf.app.web.generic.GenericLazyDataModel;
import com.emerdaf.app.web.util.MessageFactory;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("compteBean")
@ViewScoped
public class CompteBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(CompteBean.class.getName());

    private GenericLazyDataModel<CompteEntity> lazyModel;

    private CompteEntity compte;

    @Inject
    private CompteService compteService;
    @Inject
    private NoeudService noeudService;

    @Inject
    private ClientBean clientBean;
    @Inject
    private NoeudBean noeudBean;

    private Integer categorie;

    @Inject
    private UserService userService;

    private List<UserEntity> allClientsList;
    private List<CompteEntity> comptesBase = new ArrayList<>();
    private List<CompteEntity> cmptParents = new ArrayList<>();

    public void prepareNewCompte() {
        reset();
        this.compte = new CompteEntity();
        // set any default values now, if you need
        // Example: this.compte.setAnything("test");
    }

    public GenericLazyDataModel<CompteEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(compteService);
        }
        return this.lazyModel;
    }

    public List<CompteEntity> getComptesBase() {
        return compteService.compteBase();
    }

    public void setComptesBase(List<CompteEntity> comptesBase) {
        this.comptesBase = comptesBase;
    }

    public Integer getCategorie() {
        return categorie;
    }

    public void setCategorie(Integer categorie) {
        this.categorie = categorie;
    }

    public List<CompteEntity> getCmptParents() {
        return compteService.comptesParentsElligibles(compte);
    }

    public void setCmptParents(List<CompteEntity> cmptParents) {
        this.cmptParents = cmptParents;
    }

    public String persist() {

        if (compte.getId() == null && !isPermitted("compte:create")) {
            return "accessDenied";
        } else if (compte.getId() != null && !isPermitted(compte, "compte:update")) {
            return "accessDenied";
        }

        String message;

        try {

            if (compte.getId() != null) {
                compte = compteService.update(compte);
//                noeudBean.getNoeud().setCompteEnfant(compte);
//                noeudBean.persist();
                message = "message_successfully_updated";
            } else {
                compte = compteService.save(compte);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);

        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);

        return null;
    }

    public String delete() {

        if (!isPermitted(compte, "compte:delete")) {
            return "accessDenied";
        }

        String message;

        try {
            compteService.delete(compte);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));

        return null;
    }

    public void reset() {
        compte = null;

        allClientsList = null;

    }

    // Get a List of all client
    public List<UserEntity> getClients() {
        if (this.allClientsList == null) {
            this.allClientsList = userService.findAllUserEntities();
        }
        return this.allClientsList;
    }

    // Update client of the current compte
    public void updateClient(UserEntity user) {
        this.compte.setClient(user);
        // Maybe we just created and assigned a new user. So reset the allClientList.
        allClientsList = null;
    }

    public SelectItem[] getStatusSelectItems() {
        SelectItem[] items = new SelectItem[CompteStatus.values().length];

        int i = 0;
        for (CompteStatus status : CompteStatus.values()) {
            items[i++] = new SelectItem(status, getLabelForStatus(status));
        }
        return items;
    }

    public String getLabelForStatus(CompteStatus value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_compte_status_" + value);
        return label == null ? value.toString() : label;
    }

    public CompteEntity getCompte() {
        if (this.compte == null) {
            prepareNewCompte();
        }
        return this.compte;
    }

    public void setCompte(CompteEntity compte) {
        this.compte = compte;
    }

    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(CompteEntity compte, String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public String creerCompteBase() {
        compte.setStatus(CompteStatus.PAYE);
        UserEntity user = clientBean.getClient();
        compte.setClient(user);
        compte.setType("EMERDAF");
        persist();
        for (int i = 0; i < 3; i++) {
            NoeudEntity noeudEntity = new NoeudEntity();
            noeudEntity.setCompteParent(compte);
            noeudService.save(noeudEntity);
        }
        return null;
    }

    public String creerCompte() {
        compte.setStatus(CompteStatus.NONPAYE);
        UserEntity user = clientBean.getClient();
        compte.setClient(user);
        compte.setType("CLIENT");
        persist();
        NoeudEntity noeudEntity = new NoeudEntity();
        noeudEntity.setCompteEnfant(compte);
        noeudService.save(noeudEntity);
        return null;
    }

    public CompteEntity compteParent(CompteEntity c) {
        return compteService.getParent(c);
    }

}

src/main/webapp/pages/compte/cmptAdmin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
    <ui:composition template="/templates/layout.xhtml">
        <ui:define name="content">

            <f:metadata>
                <f:viewParam name="id" value="#{compteBean.compte}" converter="#{genericEntityConverter}" />
            </f:metadata>

            <p:outputPanel id="compteEditPanel">
                <h:form id="editCompteForm">
                    <p:panelGrid rendered="#{p:ifGranted('Administrator')}" columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">

                        <h:outputLabel value="#{messages.field_label_compte_categorie}:" for="categorieEditInput1" />
                        <p:inputText value="#{compteBean.compte.categorie}"  id="categorieEditInput1" 
                                     label="#{messages.field_label_compte_categorie}" />
                        <p:message for="categorieEditInput1" display="icon" />

                    </p:panelGrid>
                    <div style="margin:10px">
                        <p:commandButton value="#{messages.label_save}" icon="ui-icon-disk" actionListener="#{compteBean.creerCompteBase}"
                                         action="/pages/compte/compteBase?faces-redirect=true" update=":compteEditPanel :growlForm:growl" />
                        <p:commandButton value="#{messages.label_close}" icon="ui-icon-close"
                                         action="/pages/compte/compteBase?faces-redirect=true" immediate="true" />
                    </div>
                </h:form>
            </p:outputPanel>

        </ui:define>

    </ui:composition>
</html>

src/main/webapp/pages/compte/compte.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
    <ui:composition template="/templates/layout.xhtml">
        <ui:define name="content">

             <!--
          Comptes client
            -->
            
            <h:form rendered="#{p:ifGranted('Registered')}">
                <p:commandButton value="#{messages.create_new_compte}" icon="ui-icon-plusthick"
                                 action="/pages/compte/cmptClient?faces-redirect=true"
                                 />

                <br></br>
                <hr></hr>
                <ui:repeat value="#{clientBean.comptes}" var="cmpt">
                    <div>
                        <h:outputLabel value="ID COMPTE : #{cmpt.id}"/><br></br>
                        <h:outputLabel value="CATEGORIE : #{cmpt.categorie} FC"/><br></br>
                        <h:outputLabel value="COMPTE PARENT : #{compteBean.compteParent(cmpt).id}"/><br></br>
                        <h:outputLabel value="COMPTE STATUS : #{cmpt.status}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS : #{clientBean.getNbreEnfs(cmpt)}"/><br></br>
                        <h:outputLabel value="MONEY : #{clientBean.getNbreEnfs(cmpt) * cmpt.categorie /10}"/><br></br>
                        <BR></BR>
                        <h:outputLabel value="NOMBRE D'ENFANTS 1: #{clientBean.nbreEnfParNiveau[0]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 2: #{clientBean.nbreEnfParNiveau[1]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 3: #{clientBean.nbreEnfParNiveau[2]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 4: #{clientBean.nbreEnfParNiveau[3]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 5: #{clientBean.nbreEnfParNiveau[4]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 6: #{clientBean.nbreEnfParNiveau[5]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 7: #{clientBean.nbreEnfParNiveau[6]}"/><br></br>

                    </div>
                    <hr></hr>
                </ui:repeat>
            </h:form>

            <!--
            Gestion des comptes par l'admin
            -->
            
            <h:form prependId="false" id="compteDataForm" rendered="#{p:ifGranted('Administrator')}" onkeypress="if (event.keyCode == 13) {
                        return false;
                    }">

                <p:dataTable id="compteTable" value="#{compteBean.lazyModel}" var="compte" resizableColumns="true" paginator="true"
                             paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true" lazy="true"
                             paginatorPosition="bottom" widgetVar="compteTable" emptyMessage="#{messages.label_no_records_found}"
                             reflow="true">

                    <f:facet name="header" >

                        <p:commandButton value="#{messages.create_new_compte}" icon="ui-icon-plusthick"
                                         action="/pages/compte/compteCreate?faces-redirect=true"
                                         rendered="#{compteBean.isPermitted('compte:create')}" style="float:left" />

                        <p:commandButton value="Creer un compte de base" icon="ui-icon-plusthick"
                                         action="/pages/compte/cmptAdmin?faces-redirect=true"
                                         rendered="#{p:ifGranted('Administrator')}" style="float:left" />

                        <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
                        <p:columnToggler datasource="compteTable" trigger="toggler" />
                    </f:facet>
                    
                    <p:column headerText="Compte id" sortBy="#{compte.id}" filterBy="#{compte.id}">
                        <h:outputText value="#{compte.id}" ><f:convertNumber /></h:outputText>
                    </p:column>
                    
                    <p:column headerText="#{messages.field_label_compte_categorie}" sortBy="#{compte.categorie}" filterBy="#{compte.categorie}">
                        <f:facet name="filter">
                            <p:inputText id="categorieFilter"
                                         onkeypress="if (event.keyCode == 13) {
                                                     PF('compteTable').filter();
                                                     updateCategorieFilter();
                                                     return false;
                                                 }" >
                                <p:remoteCommand name="updateCategorieFilter" update="compteTable:categorieFilter" />
                                <f:convertNumber integerOnly="true" />
                            </p:inputText>
                        </f:facet>
                        <h:outputText value="#{compte.categorie}" ><f:convertNumber /></h:outputText>
                    </p:column>




                    <p:column headerText="#{messages.field_label_compte_client}" sortBy="#{compte.client}" filterBy="#{compte.client}">
                        <f:facet name="filter">
                            <p:selectOneMenu  id="clientFilter"
                                              style="width:145px;"
                                              onchange="PF('compteTable').filter();
                                                      return false;">
                                <f:selectItem noSelectionOption="true" itemLabel="" />
                                <f:selectItems itemLabel="#{user.username}"
                                               value="#{compteBean.clients}" 
                                               var="user" 
                                               itemValue="#{user}" />
                                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{compteBean.clients}" />
                            </p:selectOneMenu>
                        </f:facet>
                        <h:outputText value="#{compte.client.username}" />
                    </p:column>

                    <p:column headerText="#{messages.field_label_compte_status}"
                              sortBy="#{compte.status}" filterBy="#{compte.status}">
                        <f:facet name="filter">
                            <p:selectOneMenu id="statusFilter"
                                             style="width:145px;"
                                             onchange="PF('compteTable').filter();
                                                     return false;" >
                                <f:selectItem noSelectionOption="true" itemLabel="" />
                                <f:selectItems value="#{compteBean.statusSelectItems}" />
                            </p:selectOneMenu>
                        </f:facet>
                        <h:outputText value="#{compteBean.getLabelForStatus(compte.status)}" />
                    </p:column>

                    <p:column headerText="#{messages.field_label_noeud_compteParent}" sortBy="#{compte.categorie}" filterBy="#{compte.categorie}">
                        <h:outputText value="#{compteBean.compteParent(compte).id}" ></h:outputText>
                    </p:column>
                    <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">

                        <p:commandButton action="#{'/pages/compte/compteView?faces-redirect=true&amp;id='.concat(compte.id)}"
                                         icon="ui-icon-zoomin"
                                         title="#{messages.label_view}" />

                        <p:commandButton action="#{'/pages/compte/compteEdit?faces-redirect=true&amp;id='.concat(compte.id)}"
                                         icon="ui-icon-pencil"
                                         resetValues="true"
                                         rendered="#{compteBean.isPermitted(compte, 'compte:update')}"
                                         title="#{messages.label_edit}" />

                        <p:commandButton icon="ui-icon-close" rendered="#{compteBean.isPermitted(compte, 'compte:delete')}"
                                         oncomplete="PF('deleteCompteDialogWidget').show()"
                                         title="#{messages.label_delete}" >
                            <f:setPropertyActionListener value="#{compte}"
                                                         target="#{compteBean.compte}" />
                        </p:commandButton>

                    </p:column>

                </p:dataTable>

            </h:form>

            <p:confirmDialog id="deleteCompteDialog" widgetVar="deleteCompteDialogWidget"
                             rendered="#{compteBean.isPermitted(compteBean.compte, 'compte:delete')}" header="#{messages.label_confirm_deletion}"
                             severity="alarm">
                <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
                <p:outputPanel>
                    <h:form>
                        <div style="text-align: center; margin:10px">
                            <p:commandButton value="#{messages.label_yes}" action="#{compteBean.delete}" update=":compteDataForm :growlForm:growl" oncomplete="PF('deleteCompteDialogWidget').hide()" />
                            <p:commandButton value="#{messages.label_no}" onclick="PF('deleteCompteDialogWidget').hide()" type="button" />
                        </div>
                    </h:form>
                </p:outputPanel>
            </p:confirmDialog>

        </ui:define>
    </ui:composition>
</html>

src/main/webapp/pages/compte/compteBase.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
    <ui:composition template="/templates/layout.xhtml">
        <ui:define name="content">

            <!--
         Comptes client
            -->

            <h:form rendered="#{p:ifGranted('Registered')}">
                <p:commandButton value="#{messages.create_new_compte}" icon="ui-icon-plusthick"
                                 action="/pages/compte/cmptClient?faces-redirect=true"
                                 />

                <br></br>
                <hr></hr>
                <ui:repeat value="#{clientBean.comptes}" var="cmpt">
                    <div>
                        <h:outputLabel value="ID COMPTE : #{cmpt.id}"/><br></br>
                        <h:outputLabel value="CATEGORIE : #{cmpt.categorie} FC"/><br></br>
                        <h:outputLabel value="COMPTE PARENT : #{compteBean.compteParent(cmpt).id}"/><br></br>
                        <h:outputLabel value="COMPTE STATUS : #{cmpt.status}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS : #{clientBean.getNbreEnfs(cmpt)}"/><br></br>
                        <h:outputLabel value="MONEY : #{clientBean.getNbreEnfs(cmpt) * cmpt.categorie /10}"/><br></br>
                        <BR></BR>
                        <h:outputLabel value="NOMBRE D'ENFANTS 1: #{clientBean.nbreEnfParNiveau[0]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 2: #{clientBean.nbreEnfParNiveau[1]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 3: #{clientBean.nbreEnfParNiveau[2]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 4: #{clientBean.nbreEnfParNiveau[3]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 5: #{clientBean.nbreEnfParNiveau[4]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 6: #{clientBean.nbreEnfParNiveau[5]}"/><br></br>
                        <h:outputLabel value="NOMBRE D'ENFANTS 7: #{clientBean.nbreEnfParNiveau[6]}"/><br></br>

                    </div>
                    <hr></hr>
                </ui:repeat>
            </h:form>

            <!--
            Gestion des comptes par l'admin
            -->

            <h:form prependId="false" id="compteDataForm" rendered="#{p:ifGranted('Administrator')}" onkeypress="if (event.keyCode == 13) {
                        return false;
                    }">

                <p:dataTable id="compteTable" value="#{compteBean.lazyModel}" var="compte" resizableColumns="true" paginator="true"
                             paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true" lazy="true"
                             paginatorPosition="bottom" widgetVar="compteTable" emptyMessage="#{messages.label_no_records_found}"
                             reflow="true">

                    <f:facet name="header" >

                        <p:commandButton value="Creer un compte de base" icon="ui-icon-plusthick"
                                         action="/pages/compte/cmptAdmin?faces-redirect=true"
                                         rendered="#{p:ifGranted('Administrator')}" style="float:left" />

                        <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
                        <p:columnToggler datasource="compteTable" trigger="toggler" />
                    </f:facet>

                    <p:column headerText="Compte id" sortBy="#{compte.id}" filterBy="#{compte.id}">
                        <h:outputText value="#{compte.id}" ><f:convertNumber /></h:outputText>
                    </p:column>

                    <p:column headerText="#{messages.field_label_compte_categorie}" sortBy="#{compte.categorie}" filterBy="#{compte.categorie}">
                        <f:facet name="filter">
                            <p:inputText id="categorieFilter"
                                         onkeypress="if (event.keyCode == 13) {
                                                     PF('compteTable').filter();
                                                     updateCategorieFilter();
                                                     return false;
                                                 }" >
                                <p:remoteCommand name="updateCategorieFilter" update="compteTable:categorieFilter" />
                                <f:convertNumber integerOnly="true" />
                            </p:inputText>
                        </f:facet>
                        <h:outputText value="#{compte.categorie}" ><f:convertNumber /></h:outputText>
                    </p:column>




                    <p:column headerText="#{messages.field_label_compte_client}" sortBy="#{compte.client}" filterBy="#{compte.client}">
                        <f:facet name="filter">
                            <p:selectOneMenu  id="clientFilter"
                                              style="width:145px;"
                                              onchange="PF('compteTable').filter();
                                                      return false;">
                                <f:selectItem noSelectionOption="true" itemLabel="" />
                                <f:selectItems itemLabel="#{user.username}"
                                               value="#{compteBean.clients}" 
                                               var="user" 
                                               itemValue="#{user}" />
                                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{compteBean.clients}" />
                            </p:selectOneMenu>
                        </f:facet>
                        <h:outputText value="#{compte.client.username}" />
                    </p:column>

                    <p:column headerText="#{messages.field_label_compte_status}"
                              sortBy="#{compte.status}" filterBy="#{compte.status}">
                        <f:facet name="filter">
                            <p:selectOneMenu id="statusFilter"
                                             style="width:145px;"
                                             onchange="PF('compteTable').filter();
                                                     return false;" >
                                <f:selectItem noSelectionOption="true" itemLabel="" />
                                <f:selectItems value="#{compteBean.statusSelectItems}" />
                            </p:selectOneMenu>
                        </f:facet>
                        <h:outputText value="#{compteBean.getLabelForStatus(compte.status)}" />
                    </p:column>

                    <p:column headerText="#{messages.field_label_noeud_compteParent}" sortBy="#{compte.categorie}" filterBy="#{compte.categorie}">
                        <h:outputText value="#{compteBean.compteParent(compte).id}" ></h:outputText>
                    </p:column>
                    <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">

                        <p:commandButton action="#{'/pages/compte/compteView?faces-redirect=true&amp;id='.concat(compte.id)}"
                                         icon="ui-icon-zoomin"
                                         title="#{messages.label_view}" />

                        <p:commandButton action="#{'/pages/compte/compteEdit?faces-redirect=true&amp;id='.concat(compte.id)}"
                                         icon="ui-icon-pencil"
                                         resetValues="true"
                                         rendered="#{compteBean.isPermitted(compte, 'compte:update')}"
                                         title="#{messages.label_edit}" />

                        <p:commandButton icon="ui-icon-close" rendered="#{compteBean.isPermitted(compte, 'compte:delete')}"
                                         oncomplete="PF('deleteCompteDialogWidget').show()"
                                         title="#{messages.label_delete}" >
                            <f:setPropertyActionListener value="#{compte}"
                                                         target="#{compteBean.compte}" />
                        </p:commandButton>

                    </p:column>

                </p:dataTable>

            </h:form>

            <p:confirmDialog id="deleteCompteDialog" widgetVar="deleteCompteDialogWidget"
                             rendered="#{compteBean.isPermitted(compteBean.compte, 'compte:delete')}" header="#{messages.label_confirm_deletion}"
                             severity="alarm">
                <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
                <p:outputPanel>
                    <h:form>
                        <div style="text-align: center; margin:10px">
                            <p:commandButton value="#{messages.label_yes}" action="#{compteBean.delete}" update=":compteDataForm :growlForm:growl" oncomplete="PF('deleteCompteDialogWidget').hide()" />
                            <p:commandButton value="#{messages.label_no}" onclick="PF('deleteCompteDialogWidget').hide()" type="button" />
                        </div>
                    </h:form>
                </p:outputPanel>
            </p:confirmDialog>

        </ui:define>
    </ui:composition>
</html>

src/main/webapp/pages/compte/compteCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <ui:include src="/pages/compte/compteEdit.xhtml" />

</html>